import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('standalone dashboard bundle uses REST + SSE and contains no embedded MCP Apps transport', async () => {
  const html = await readFile(new URL('../ui/dist/index.html', import.meta.url), 'utf8')

  assert.doesNotMatch(html, /dhtmlx|dhx-gantt-icons/i)
  assert.doesNotMatch(html, /fonts\.gstatic\.com/)
  assert.doesNotMatch(html, /cdn\.svar\.dev|https?:\/\/[^)'\"]+\.(?:woff2?|ttf)/i)
  assert.match(html, /wx-gantt/)
  assert.doesNotMatch(html, /license.?key|APEXCHARTS|trial watermark/i)
  assert.doesNotMatch(html, /Auth Refactor|Investigate API timeout/)
  assert.doesNotMatch(html, /@modelcontextprotocol\/ext-apps|callServerTool|agent_tasks_dashboard|dashboard-v1\.html/)
  assert.equal((html.match(/^<script\b/gm) ?? []).length, 1)
  assert.equal((html.match(/^<\/script>/gm) ?? []).length, 1)
  assert.ok(Buffer.byteLength(html) < 2 * 1024 * 1024)
  assert.match(html, /\/api\/v1\/snapshot/)
  assert.match(html, /\/api\/v1\/events/)
  assert.match(html, /EventSource/)
  assert.match(html, /dashboard-grid-width/)
  assert.match(html, /svar-timeline-separator/)
  assert.match(html, /current-time-marker/)
  assert.match(html, /renderer-error-state/)
  assert.match(html, /role:\"alert\"/)
  assert.match(html, /execution-inbox/)
  assert.match(html, /\.inbox-actions button\{min-width:32px;min-height:36px\}/)
  assert.match(html, /\.session-copy\{width:24px;height:24px;flex-basis:24px;[^}]*\}/)
  assert.match(html, /--wx-grid-body-cell-border:1px solid transparent/)
  assert.match(html, /\.svar-gantt-shell \.wx-bar\{[^}]*border-radius:3px/)
  assert.match(html, /\.current-time-marker span\{display:none\}/)
  assert.match(html, /\/api\/v1\/executions\/tasks/)
  assert.doesNotMatch(html, /getLayoutView\?\.\(["']grid["']\)\?\.\$view/)
  assert.doesNotMatch(html, /DHTMLX Gantt Standard 9\.1 · GPL-2\.0 · SQLite 实时视图/)
  assert.doesNotMatch(html, /class="license-note"/)
})
